# Generated by Django 2.2.17 on 2020-12-30 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oranizations', '0003_auto_20201230_0958'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oranizations.CourseOrg', verbose_name='所属机构'),
        ),
    ]
