# Generated by Django 2.2.17 on 2020-12-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='index',
            field=models.IntegerField(verbose_name='顺序'),
        ),
    ]
