# Generated by Django 2.2.17 on 2021-01-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210119_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('update_email', '修改邮箱')], max_length=30),
        ),
    ]
