# Generated by Django 2.2.17 on 2020-12-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oranizations', '0003_auto_20201230_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
